### PR TITLE
Debugging coverage

### PR DESCRIPTION
**Pull request by stevepeak**
Debugging coverage. Please do not merge. Thank you!

### CODE REVIEW

**Comment by stevepeak** [comment]
Looks like Jacoco reports that line as missed:
```
...<sourcefile name="Extensions.kt"><line nr="1" mi="3" ci="0" mb="0" cb="0"/>...
```

I can adjust for this in our backend. Are all the files `.kt` that are experiencing this issue?

**Comment by jkcclemens** [comment]
Before, the `JSONCardReader.kt` file was experiencing this issue, but now it is only all of the `Extensions.kt` files in the `xyz.cardstock.cardstock.extensions` package.

**Comment by stevepeak** [comment]
No problem. Given this is an issue is with Jacoco, I can update the uploader to especially skip the first line on file (if it is a comment). Sound good?

**Comment by jkcclemens** [comment]
Sounds good to me. If I have the issue on any other comments, I'll be sure to let you know.

**Comment by stevepeak** [comment]
@jkcclemens do you know why `JSONCardReader.kt` had the issue ..then.. didn't?

**Comment by jkcclemens** [comment]
I have no idea at all.

**Comment by stevepeak** [comment]
Would `.kt` files **ever** have Line 1 actual code? I'm trying to figure out the best place to hack this fix.

**Comment by jkcclemens** [comment]
It's possible, for sure.

**Comment by jkcclemens** [comment]
Just for an example,

```kotlin
fun main(args: Array<out String>) {
    println("Hello!")
}
```
as a file is completely valid.

**Comment by jkcclemens** [comment]
Any updates on this?

**Comment by stevepeak** [comment]
I know what I must do, but unfortunately I have other items on my chopping block atm. I'll try to get to this asap :)

**Comment by jkcclemens** [comment]
I don't know if this is related, but there's one partial line on [this](https://codecov.io/github/jkcclemens/khttp/src/main/kotlin/me/kyleclemens/khttp/structures/cookie/CookieJar.kt?ref=c9879cc9ce24cd4e215e49518617c1dcb5803835) file, but all of the lines are green.

**Comment by stevepeak** [comment]
@jkcclemens sorry for delay, things are getting busy here! Which line are you referencing? It though there are partials they are all 100% hit. 

I hope to get into this issue this week one I fry other big fish :fish:

**Comment by jkcclemens** [comment]
I don't know what line I'm referring to! If you look at the top right, it says "28 hits" and "1 partial," even though all of the lines appear to be green.

**Comment by stevepeak** [comment]
Good news! I've got progress on the comment line: https://github.com/codecov/codecov-bash/commit/28e49aac8fc5fe000613862ff106bba391d0a100#diff-45b1150df0237fb1cb2a238a2d04554eR652

Checkout out the [report data here](https://codecov.io/api/github/jkcclemens/khttp/src/main/kotlin/me/kyleclemens/khttp/structures/cookie/CookieJar.kt?ref=c9879cc9ce24cd4e215e49518617c1dcb5803835)... look like lines that not in the file. I'll make some tweaks to inspect.

**Comment by jkcclemens** [comment]
Weird. I suppose you could just ignore lines that aren't within the range of the file, if a root cause can't be found.

Thanks a million for working on these issues!

**Comment by stevepeak** [comment]
Your welcome :+1: 

This issue is odd... there must be some root issues in jacoco and kotlin that I have not seen before.

**Pull request closed without merging**
